<?php
return [
    'en' => [
        'adult_name_required' => 'Traveler Name is required',
        'child_name_required' => 'Traveler Name is required',
        'infant_name_required' => 'Traveler Name is required',
        'adult_surname_required' => 'Traveler Surname is required',
        'child_surname_required' => 'Traveler Surname is required',
        'infant_surname_required' => 'Traveler Surname is required',
        'adult_birth_date_required' => 'Traveler Birth Day is required',
        'adult_birth_date_date' => 'Birth Day must be valid',
        'child_birth_date_required' => 'Traveler Birth Day is required',
        'child_birth_date_date' => 'Birth Day must be valid',
        'infant_birth_date_required' => 'Traveler Birth Day is required',
        'infant_birth_date_date' => 'Birth Day must be valid',
    ],
    'ru' => [
        'adult_name_required' => 'Необходимо указать имя',
        'child_name_required' => 'Необходимо указать имя',
        'infant_name_required' => 'Необходимо указать имя',
        'adult_surname_required' => 'Необходимо указать фамилию',
        'child_surname_required' => 'Необходимо указать фамилию',
        'infant_surname_required' => 'Необходимо указать фамилию',
        'adult_birth_date_required' => 'Необходимо указать дату рождения',
        'adult_birth_date_date' => 'Необходимо указать правильную дату',
        'child_birth_date_required' => 'Необходимо указать дату рождения',
        'child_birth_date_date' => 'Необходимо указать правильную дату',
        'infant_birth_date_required' => 'Необходимо указать дату рождения',
        'infant_birth_date_date' => 'Необходимо указать правильную дату',
    ],
];